### ISSUE TITLE
Fix up - van to van transfers in the job

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#115]

**Comment by bLeenstra** [comment]
More information required.
What do you need here?

**Comment by samuelGrahame** [comment]
- at the moment, van to van transfers on a job. will do the stock movement - then quickly save the job and re modify - there could be issues with this functionality - etc if there are programmed action plans.

an employee could also remove the charge customer, then change the technician - remove the parts. then cancel modify and repeat.

i have added a permission so that they cannot do this by default
