### ISSUE TITLE
Action Plans - Trigger()

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#206]
Does this work correctly? I have setup an action plan in our test environment but nothing happened.

![image](https://user-images.githubusercontent.com/36732084/41520346-cc16d4fa-72ff-11e8-9ca0-9c60f876a129.png)

**Comment by bLeenstra** [comment]
Issue with Trigger(Open Payment Screen)
Currently does not work with sales

**Comment by bLeenstra** [comment]
Hi Anthony,

Follow up here, currently this action plan will work in the OnLoading Section, but not the Saving and Saved sections of the action plans. This is because you cannot actually open the payment screen while a job is modified, which it still is while saving the repair.

I will see if i can change this so that it will open with the saved action plan

**Comment by bLeenstra** [comment]
Fixed for v370
   - The OnSaved Action plan was never ran for the sales screen. I have fixed this.
   - If the action plan you have linked is in OnSaving you will need to move it to the OnSaved event.
