### ISSUE TITLE
Departments - Transfer stock prompt - for jobs.

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#207]
Stock prompt to give option to transfer parts between departments rather than ordering additional parts

**Comment by samuelGrahame** [comment]
for this to work
we need to create a department order item. so that way it will create an internal order, that that department can mark as sent - etc each item

then the first department can accept received.

as these part's will have a freight charge added to the requested department. or nominated account. 

i could see this getting messy. as each department need to make sure the correct stock level's are showing
