### ISSUE TITLE
Return slips - Technician name based of return location or primary allocation

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#226]
There appears to be an error now with the picking slips, 2 engineers have been combined under the same Van12 - Could you please fix this ASAP

![image](https://user-images.githubusercontent.com/39507077/41766792-474ea1ae-764b-11e8-81a6-f2a67ad56ae3.png)

**Comment by bLeenstra** [comment]
Hi, as mentioned in relation the technician name on the picking slip screen, we used the primary allocation technician name, rather than the transfer to van name.

The assigned technician will not always be the transfer to van.

We added this feature like this as you where having trouble with order parts where the to location was the warehouse.
I can change this to be based on van if you want, however you wouldn't find any additional benefit to the senario explained above

**Comment by bLeenstra** [comment]
Closed as per phone conversation

**Comment by bLeenstra** [comment]
Removed images with identifying information
