### ISSUE TITLE
Jobs - Start Stop button 

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#315]
Can we force technician to enter the service report prior to putting a stop the job without leaving the service report blank?

Also, can we force tech to remove unwanted parts off and add parts used to top section prior to changing stats completed.

**Comment by samuelGrahame** [comment]
Until their is an app, we cannot force stuff like this, as if we return with an error. it will wipe all changes that they have made. etc charges/extra numbers serial numbers.

**Comment by samuelGrahame** [comment]
Because of the design of the web framework. we don't know what stage they are in.
they might want to save the serial number. but they have not finished doing their work. 

regarding the part's. we do not know what is used and un-used.

what happens if they just remove all. so they don't get this message.
also this is at the end of the job. they might not know which part's they added and didn't

I high suggest for the technician to add the part up. when they do it at the customer's place.
then they just remove the parts they didn't use. doing this method will be more accurate.

**Comment by samuelGrahame** [comment]
we really do want to make an app. so that it can be more stream lined.

for instance. i can understand that removing parts can take a while.
